name: exggagetrail
favicon: null
layout_spectrum: 0
typography_spectrum: 0.40404
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#52b2c0'
    - '#53b0bf'
    - '#50b1bf'
    - '#52b0c0'
    - '#53b0c0'
  brandStrength: 0.3125
  lightness: 0.018033507512882352
  saturation: 0.28432397870346904
  rhythmicContrast: 0.7313703333493322
purpose: []
